import 'dotenv/config';

const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
const DISCORD_APPLICATION_ID = process.env.DISCORD_APPLICATION_ID;
const AKINATOR_REGION = process.env.AKINATOR_REGION ?? 'en';
const AKINATOR_CHILD_MODE = process.env.AKINATOR_CHILD_MODE ?? false;
const AKINATOR_PROXY = process.env.AKINATOR_PROXY ?? undefined;
const AKINATOR_WIN_PROGRESS = process.env.AKINATOR_WIN_PROGRESS ?? 100;
const AKINATOR_WIN_EVERY_STEP = process.env.AKINATOR_WIN_EVERY_STEP ?? 20;
const AKINATOR_MAX_RESPONSE_MINUTE = process.env.AKINATOR_MAX_RESPONSE_MINUTE ?? 1;
const AKINATOR_MAX_GUESS_COUNT = process.env.AKINATOR_MAX_GUESS_COUNT ?? 3;

export {
    DISCORD_TOKEN,
    DISCORD_APPLICATION_ID,
    AKINATOR_REGION,
    AKINATOR_CHILD_MODE,
    AKINATOR_PROXY,
    AKINATOR_WIN_PROGRESS,
    AKINATOR_WIN_EVERY_STEP,
    AKINATOR_MAX_RESPONSE_MINUTE,
    AKINATOR_MAX_GUESS_COUNT,
};
